Remove try/catch block on unique_resource move constructor
The clang-21 says:

include/nonstd/scope.hpp:1007:40: error:
      cannot refer to a non-static member from the handler of a constructor function try block
      [-Werror,-Wexceptions]
 1007 |             other.get_deleter()( this->get() );
      |                                        ^
1 error generated.

Since the move constructor already provides an noexcept guarantee,
no exceptions will be thrown here. The try-catch block is redundant.

And a further approach is to provide a throwable exception variant of
the move constructor.